/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */

plugins {
    application
}

application {
    mainClass.set("com.ejercicio1_clase28.Main") // Ajusta esto si tienes un paquete específico
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'mysql:mysql-connector-java:8.0.34' // Cambia la versión según necesites
}
